In [12]:
import numpy as np


In [31]:
t = [[4,5,90],[3,4,8]]


In [32]:
r = np.array(t)
r

array([[ 4,  5, 90],
       [ 3,  4,  8]])

In [33]:
r.shape

(2, 3)

In [38]:
r.dtype

dtype('int32')

In [47]:
np.ndarray([2,3])

array([[7.74860419e-304, 7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304]])

In [48]:
np.ndarray([2,3])

array([[7.74860419e-304, 7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304]])

In [49]:
r.ndim

2

In [50]:
r.itemsize

4

In [53]:
r.nbytes

24

In [54]:
r


array([[ 4,  5, 90],
       [ 3,  4,  8]])

In [55]:
r.data

In [56]:
r.base

In [57]:
print(r.base)

None


In [76]:
numpy.ndarray.flat(r)

NameError: name 'numpy' is not defined

In [83]:
r = np.arange(4,20).reshape(4,4)

In [84]:
r

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [95]:
r.flatten()

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [96]:
r

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [99]:
e = r.flatten()
e

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [100]:
r

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [106]:
r = r.reshape(8,2,1,1,1,1,1)

In [107]:
r

array([[[[[[[ 4]]]]],




        [[[[[ 5]]]]]],





       [[[[[[ 6]]]]],




        [[[[[ 7]]]]]],





       [[[[[[ 8]]]]],




        [[[[[ 9]]]]]],





       [[[[[[10]]]]],




        [[[[[11]]]]]],





       [[[[[[12]]]]],




        [[[[[13]]]]]],





       [[[[[[14]]]]],




        [[[[[15]]]]]],





       [[[[[[16]]]]],




        [[[[[17]]]]]],





       [[[[[[18]]]]],




        [[[[[19]]]]]]])

In [110]:
r = r.flatten()

In [111]:
r

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [112]:
r

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [113]:
r.fill(45)

In [114]:
r

array([45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45])

In [115]:
r.shape

(16,)

In [117]:
r = r.reshape(8,2,1,1,1)
r.shape

(8, 2, 1, 1, 1)

In [129]:
r = r.reshape(8,2)

In [137]:
r.transpose(1,0)

array([[45, 45, 45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45, 45, 45]])

In [138]:
r.transpose()

array([[45, 45, 45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45, 45, 45]])

In [142]:
r.transpose([0,1])

array([[45, 45],
       [45, 45],
       [45, 45],
       [45, 45],
       [45, 45],
       [45, 45],
       [45, 45],
       [45, 45]])

In [143]:
r.shape

(8, 2)

In [144]:
r.resize(8,2,1,1)
r.shape

(8, 2, 1, 1)

In [145]:
r

array([[[[45]],

        [[45]]],


       [[[45]],

        [[45]]],


       [[[45]],

        [[45]]],


       [[[45]],

        [[45]]],


       [[[45]],

        [[45]]],


       [[[45]],

        [[45]]],


       [[[45]],

        [[45]]],


       [[[45]],

        [[45]]]])

In [147]:
r.ravel()

array([45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45])

In [156]:
r = np.ndarray([2,4])
r

array([[8.91477191e-313, 0.00000000e+000, 3.62633684e+228,
        1.01506633e+242],
       [4.25114309e-096, 9.78750380e+199, 6.97843734e+252,
        2.62461912e-306]])

In [160]:
len(r.repeat(2))

16

In [159]:
r

array([[8.91477191e-313, 0.00000000e+000, 3.62633684e+228,
        1.01506633e+242],
       [4.25114309e-096, 9.78750380e+199, 6.97843734e+252,
        2.62461912e-306]])

In [161]:
len(r)

2

In [162]:
r

array([[8.91477191e-313, 0.00000000e+000, 3.62633684e+228,
        1.01506633e+242],
       [4.25114309e-096, 9.78750380e+199, 6.97843734e+252,
        2.62461912e-306]])

In [163]:
r.repeat(3)

array([8.91477191e-313, 8.91477191e-313, 8.91477191e-313, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 3.62633684e+228, 3.62633684e+228,
       3.62633684e+228, 1.01506633e+242, 1.01506633e+242, 1.01506633e+242,
       4.25114309e-096, 4.25114309e-096, 4.25114309e-096, 9.78750380e+199,
       9.78750380e+199, 9.78750380e+199, 6.97843734e+252, 6.97843734e+252,
       6.97843734e+252, 2.62461912e-306, 2.62461912e-306, 2.62461912e-306])

In [164]:
r.shape

(2, 4)

In [165]:
r

array([[8.91477191e-313, 0.00000000e+000, 3.62633684e+228,
        1.01506633e+242],
       [4.25114309e-096, 9.78750380e+199, 6.97843734e+252,
        2.62461912e-306]])

In [173]:
r.compress(np.random.randn(1),0)

array([[8.91477191e-313, 0.00000000e+000, 3.62633684e+228,
        1.01506633e+242]])

In [176]:
r = np.ndarray(10)

In [177]:
r

array([-0.18412965,  0.68552364, -0.19531435, -0.90147359,  0.48632629,
        0.36003503,  2.99460837, -0.28114352,  1.90100601,  0.79079788])

In [178]:
r[3] = 45

In [179]:
r

array([-0.18412965,  0.68552364, -0.19531435, 45.        ,  0.48632629,
        0.36003503,  2.99460837, -0.28114352,  1.90100601,  0.79079788])

In [181]:
r[2] = 0
r[3] = 0

In [184]:
r.nonzero()

(array([0, 1, 4, 5, 6, 7, 8, 9], dtype=int32),)

In [185]:
r.sort()

In [186]:
r

array([-0.28114352, -0.18412965,  0.        ,  0.        ,  0.36003503,
        0.48632629,  0.68552364,  0.79079788,  1.90100601,  2.99460837])

In [187]:
r.copy()

array([-0.28114352, -0.18412965,  0.        ,  0.        ,  0.36003503,
        0.48632629,  0.68552364,  0.79079788,  1.90100601,  2.99460837])

In [188]:
r

array([-0.28114352, -0.18412965,  0.        ,  0.        ,  0.36003503,
        0.48632629,  0.68552364,  0.79079788,  1.90100601,  2.99460837])

In [189]:
type(r.copy())

numpy.ndarray

In [191]:
r.dump('ddd.txt')


In [195]:
r.astype(float)

NameError: name 'float64' is not defined

In [196]:
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint32,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int32,
 'p': numpy.int32,
 'uintp': numpy.uint32,
 'P': numpy.uint32,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 9: numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 10: numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float64,
 'g': numpy.float64,
 13: numpy.float64,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14: numpy.complex64,
 'c

In [197]:
np.uint64

numpy.uint64

In [203]:
np.sctypeDict['complex128']

numpy.complex128

In [205]:
np.float64([4.5234234,3,4,-1.0,-1.2, -1, -45])

array([  4.5234234,   3.       ,   4.       ,  -1.       ,  -1.2      ,
        -1.       , -45.       ])

In [212]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [219]:
np.finfo(np.float32)

finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

In [220]:
a = np.arange(5, dtype= 'u')

TypeError: data type "u" not understood

In [225]:
r.dtype

dtype('float64')

In [229]:
r.astype(dtype = np.bool)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [232]:
r

array([-0.28114352, -0.18412965,  0.        ,  0.        ,  0.36003503,
        0.48632629,  0.68552364,  0.79079788,  1.90100601,  2.99460837])

In [234]:
t = np.random.randn(2,3)
t

array([[ 1.64352195, -0.58585763, -1.52860469],
       [ 0.59778627, -0.16820929, -0.52880903]])

In [239]:
t.min(axis=0)

array([ 0.59778627, -0.58585763, -1.52860469])

In [240]:
t = np.random.randn(100,2,3)

In [242]:
t.min(axis=0)

array([[-2.60006498, -2.65180165, -3.65656549],
       [-2.40464352, -1.91291349, -1.92577573]])

In [243]:
t.argmin(axis=0)

array([[13, 94, 44],
       [20, 23,  8]], dtype=int32)

In [248]:
t[94]


array([[-0.63689786, -2.65180165,  1.88955141],
       [ 0.65173908, -0.3133518 , -0.92355183]])

In [250]:
t.ptp(axis=1)

array([[0.70068149, 1.8107279 , 0.90941393],
       [0.40769911, 1.20596878, 0.47753064],
       [0.41262251, 1.83029859, 2.91660562],
       [0.48051449, 1.11574566, 0.39781299],
       [0.06089596, 0.65975175, 2.00039253],
       [1.55874102, 0.26344411, 0.32699289],
       [1.10605344, 1.98185183, 0.10930457],
       [0.80376532, 0.07721389, 0.82170987],
       [0.63602062, 1.17689682, 2.02981936],
       [0.32008675, 2.85190205, 0.46608342],
       [1.35835418, 0.41913079, 1.2446339 ],
       [1.62427221, 1.31603483, 1.04963259],
       [0.36420859, 0.31666159, 1.43135454],
       [0.72137678, 0.23788152, 0.6730357 ],
       [1.4824359 , 0.13847592, 3.35577783],
       [1.23830421, 4.10363586, 1.87476869],
       [1.27502424, 0.50681098, 0.47238544],
       [1.66537324, 1.88662828, 0.79465295],
       [0.2122089 , 1.55130205, 1.76619149],
       [1.45919945, 2.82899752, 2.4313791 ],
       [4.91717831, 0.04297759, 1.06040559],
       [1.00043272, 2.11404832, 0.1120716 ],
       [1.

In [264]:
t = np.random.randn(3,3,4)
t

array([[[ 0.52473829, -0.75619247, -0.19757501, -0.03477157],
        [ 0.2759615 , -0.12245341, -0.45247228,  0.74135502],
        [ 1.85184909, -1.03554503, -1.5128741 ,  0.49648834]],

       [[-0.16206168, -0.87666232,  1.45810449, -0.05011518],
        [-0.78344488,  0.53728145,  0.30498836,  1.8064512 ],
        [ 0.72575171,  1.50589273, -0.40659726, -0.85034279]],

       [[-0.70891575,  1.10121763, -0.14546434, -0.29235969],
        [-0.29462676, -0.18251313, -0.92899617,  1.95767734],
        [-0.71399592,  1.35971255, -0.39307134,  1.50407469]]])

In [269]:
t.cumsum(1)

array([[[ 0.52473829, -0.75619247, -0.19757501, -0.03477157],
        [ 0.80069979, -0.87864588, -0.65004729,  0.70658346],
        [ 2.65254888, -1.91419091, -2.16292139,  1.2030718 ]],

       [[-0.16206168, -0.87666232,  1.45810449, -0.05011518],
        [-0.94550657, -0.33938087,  1.76309285,  1.75633602],
        [-0.21975486,  1.16651186,  1.35649559,  0.90599322]],

       [[-0.70891575,  1.10121763, -0.14546434, -0.29235969],
        [-1.00354251,  0.9187045 , -1.07446051,  1.66531764],
        [-1.71753843,  2.27841704, -1.46753184,  3.16939233]]])

In [272]:
x = t.__reduce__()

In [273]:
x

(<function numpy.core.multiarray._reconstruct>,
 (numpy.ndarray, (0,), b'b'),
 (1,
  (3, 3, 4),
  dtype('float64'),
  False,
  b'\xe1u\xc6\xf3\xa7\xca\xe0?P2\x05\x8f\xba2\xe8\xbfn\xcblV#J\xc9\xbf\xa3\xa7\xc0&\x94\xcd\xa1\xbf\xd3y\xafnZ\xa9\xd1?\xfb\xb0\xdcR\x1bY\xbf\xbfv\xf5yGN\xf5\xdc\xbf\xe7\xba\xe6*.\xb9\xe7?Q\xf2\xa3\x81,\xa1\xfd?Q\xadl\xa9\x97\x91\xf0\xbf\xdd\x94ex\xbb4\xf8\xbfB\xbe\xf2\x08w\xc6\xdf?\xc0\xa4y\xf1o\xbe\xc4\xbf\xcd\x1c\xbe$\x9e\r\xec\xbf\xb6\xab<_eT\xf7?\x86\x05\x11h\xb2\xa8\xa9\xbf\xe0\x94\x15\x00\xfb\x11\xe9\xbfk\xfb\x02\xe0h1\xe1?\x86\xc0z\xea\xed\x84\xd3?\xe4\\\xaf^9\xe7\xfc?\x02\'\xac\xa5[9\xe7?\x03\x0c\xca\xf9"\x18\xf8?\xac\xb4\'\x83\xb0\x05\xda\xbf+\x9a\xf9\x15\x026\xeb\xbf\xd3\x03\x1a\x16p\xaf\xe6\xbf8\xb4\xaa_\x96\x9e\xf1?\xc5_HP\x93\x9e\xc2\xbf ULo\x05\xb6\xd2\xbf`C\x8e-*\xdb\xd2\xbf\xf7&\x03\x14\x97\\\xc7\xbf@M\x8f+V\xba\xed\xbf\xcf\xdd;x\xa5R\xff?h\x04\xa6\xf9\r\xd9\xe6\xbfP=A\xf1a\xc1\xf5?m\x1cA\xae\x14(\xd9\xbf$D&\xa0\xb0\x10\xf8?'))

In [278]:
t.__lt__(0.32345)

array([[[False,  True,  True,  True],
        [ True,  True,  True, False],
        [False,  True,  True, False]],

       [[ True,  True, False,  True],
        [ True, False,  True, False],
        [False, False,  True,  True]],

       [[ True, False,  True,  True],
        [ True,  True,  True, False],
        [ True, False,  True, False]]])

In [279]:
len(t)

3

In [280]:
t

array([[[ 0.52473829, -0.75619247, -0.19757501, -0.03477157],
        [ 0.2759615 , -0.12245341, -0.45247228,  0.74135502],
        [ 1.85184909, -1.03554503, -1.5128741 ,  0.49648834]],

       [[-0.16206168, -0.87666232,  1.45810449, -0.05011518],
        [-0.78344488,  0.53728145,  0.30498836,  1.8064512 ],
        [ 0.72575171,  1.50589273, -0.40659726, -0.85034279]],

       [[-0.70891575,  1.10121763, -0.14546434, -0.29235969],
        [-0.29462676, -0.18251313, -0.92899617,  1.95767734],
        [-0.71399592,  1.35971255, -0.39307134,  1.50407469]]])

In [281]:
t.var()

0.8411656619712258

In [282]:
t.shape

(3, 3, 4)

In [283]:
t.std()

0.91715083926867

In [292]:
t.mean()

0.14584703623178236

In [293]:
t.min(), t.max(), t.mean(), t.std(), t.var()

(-1.5128740981102091,
 1.9576773354182142,
 0.14584703623178236,
 0.91715083926867,
 0.8411656619712258)

In [295]:
t.dot(t)

ValueError: shapes (3,3,4) and (3,3,4) not aligned: 4 (dim 2) != 3 (dim 1)

In [297]:
start = 50
stop = 444
step = 3
t = np.random.randn(1000)
t[start:stop:step]

array([ 0.13259656,  0.27043309, -0.63021986, -0.2295364 ,  0.07886931,
        0.37489371, -0.73416293, -0.70464053,  0.42769875, -0.41641782,
        0.34147668,  0.44646313,  0.08463984,  1.39085804,  1.28195208,
        0.31190859, -1.70692254, -0.05167559,  0.2082143 , -2.0608451 ,
        1.049023  , -0.96997709,  1.04447172,  0.35557772, -0.84319062,
        0.31167482,  1.03831746, -0.66800063, -0.55141822, -0.05972394,
        0.09641159, -0.59523117, -0.61188583, -0.97291987,  0.27994156,
       -0.96744426,  0.17124101,  0.68732336, -0.26659374, -1.65963398,
       -1.09450771, -0.53646551,  0.0478293 , -0.2209808 , -1.25767023,
       -0.93147001,  0.3289869 ,  0.81354691, -0.81938745,  1.1665371 ,
        0.24619416, -2.41955591,  0.47676283, -0.97592199, -0.82623338,
        0.66206741, -0.28926337, -1.67669518,  1.73454182, -2.78297406,
        0.83977809, -0.49233813, -0.30442944, -0.95568664,  0.50683548,
        0.56811522,  0.23786404,  0.54197779,  0.34891203, -2.28

In [299]:
t = np.random.randint(40,100, 50)
t

array([64, 64, 84, 75, 79, 81, 83, 81, 75, 52, 95, 82, 54, 90, 97, 96, 65,
       93, 53, 60, 79, 55, 67, 42, 66, 55, 59, 92, 54, 73, 70, 60, 45, 41,
       97, 68, 57, 90, 79, 77, 55, 51, 52, 74, 40, 84, 78, 73, 41, 58])

In [303]:
len(t)

50

In [306]:
t[-27:37]

array([42, 66, 55, 59, 92, 54, 73, 70, 60, 45, 41, 97, 68, 57])

In [307]:
t[-27:37:3]

array([42, 59, 73, 45, 68])

In [311]:
t[:, np.newaxis]

array([[64],
       [64],
       [84],
       [75],
       [79],
       [81],
       [83],
       [81],
       [75],
       [52],
       [95],
       [82],
       [54],
       [90],
       [97],
       [96],
       [65],
       [93],
       [53],
       [60],
       [79],
       [55],
       [67],
       [42],
       [66],
       [55],
       [59],
       [92],
       [54],
       [73],
       [70],
       [60],
       [45],
       [41],
       [97],
       [68],
       [57],
       [90],
       [79],
       [77],
       [55],
       [51],
       [52],
       [74],
       [40],
       [84],
       [78],
       [73],
       [41],
       [58]])

In [312]:
t

array([64, 64, 84, 75, 79, 81, 83, 81, 75, 52, 95, 82, 54, 90, 97, 96, 65,
       93, 53, 60, 79, 55, 67, 42, 66, 55, 59, 92, 54, 73, 70, 60, 45, 41,
       97, 68, 57, 90, 79, 77, 55, 51, 52, 74, 40, 84, 78, 73, 41, 58])

In [313]:
t[::3]

array([64, 75, 83, 52, 54, 96, 53, 55, 66, 92, 70, 41, 57, 77, 52, 84, 41])